CREATE DATABASE PROJECT;
USE PROJECT;

CREATE TABLE Studentinfo(
STU_ID INT, 
STU_NAME VARCHAR (32), 
DOB DATE, 
PHONE_NO INT, 
EMAIL_ID VARCHAR (32), 
ADDRESS VARCHAR (64));

ALTER TABLE Studentinfo
ADD CONSTRAINT PRIMARY KEY (STU_ID);

ALTER TABLE Studentinfo
RENAME TO StudentInfo;

CREATE TABLE CourseInfo(
COURSE_ID INT PRIMARY KEY, 
COURSE_NAME VARCHAR (32), 
COURSE_INSTRUCTORNAME VARCHAR (32));

CREATE TABLE EnrollmentInfo(
ENROLLMENT_ID INT, 
COURSE_ID INT, 
STU_ID INT,
ENROLL_STATUS ENUM('ENROLLED', 'NOT_ENROLLED'),
CONSTRAINT FK_STUDENT FOREIGN KEY (STU_ID) REFERENCES StudentInfo(STU_ID) ON DELETE CASCADE,
CONSTRAINT FK_COURSE FOREIGN KEY (COURSE_ID) REFERENCES CourseInfo(COURSE_ID) ON DELETE CASCADE
);